apiVersion: v1
appVersion: 2.6.1
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
icon: https://raw.githubusercontent.com/digitalocean/netbox/develop/docs/netbox_logo.png
name: netbox
version: 0.2.0
