dependencies:
- name: postgresql
  version: 5.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 8.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
